import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};
export default {
  docsSidebar: [
    'intro',  // 개발 일지 메인 문서
    {
      type: 'autogenerated',
      dirName: 'dev',  // dev 폴더 내의 모든 문서를 자동으로 포함
    },
  ],
  resourceSidebar: [
    'intro_resource',  // 자료 섹션 메인 문서
    {
      type: 'autogenerated',
      dirName: 'resource',  // resource 폴더 내의 모든 문서를 자동으로 포함
    }
  ],
};
